# Makefile for cs 455 C++ Debugger / Linked lists lab


factors: factors.cpp
	g++ -ggdb -Wall factors.cpp -o factors

factorsUpdated: factorsUpdated.cpp
	g++ -ggdb -Wall factorsUpdated.cpp -o factorsup; ./factorsup

testlist: testlist.cpp
	g++ -ggdb -Wall testlist.cpp -o testlist

testlistSumList: testlistSumList.cpp
	g++ -ggdb -Wall testlistSumList.cpp -o testlistsl; ./testlistsl

testlistAppend: testlistAppend.cpp
	g++ -ggdb -Wall testlistAppend.cpp -o testlista; ./testlista

testlistPrint: testlistPrint.cpp
	g++ -ggdb -Wall testlistPrint.cpp -o testlistp; ./testlistp